export const ADD_TO_BACKET = "ADD_TO_BACKET";
export const DEL_TO_BACKET = "DEL_TO_BACKET";
export const PRODUCT_SELECTED = "PRODUCT_SELECTED";
export const DISABLE_BUTTONS = "DISABLE_BUTTONS";
export const ENABLE_BUTTONS = "ENABLE_BUTTONS";
